# Generated by Django 4.1 on 2022-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_hotal',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='Exterior_images1',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='Exterior_images2',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='Exterior_images3',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='Exterior_images4',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='Exterior_images5',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='bedroom_images1',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='bedroom_images2',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='bedroom_images3',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='bedroom_images4',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='bedroom_images5',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='garden_images1',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='garden_images2',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='garden_images3',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='garden_images4',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='garden_images5',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='reception_images1',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='reception_images2',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='reception_images3',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='reception_images4',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='reception_images5',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='washroom_images1',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='washroom_images2',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='washroom_images3',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='washroom_images4',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='washroom_images5',
            field=models.ImageField(blank=True, null=True, upload_to='hotalmedia'),
        ),
        migrations.AlterField(
            model_name='add_hotal',
            name='hotal_new_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
