# Generated by Django 4.1 on 2022-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0002_alter_add_hotal_options_add_hotal_exterior_images1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_hotal',
            name='Hotal_images2',
        ),
        migrations.RemoveField(
            model_name='add_hotal',
            name='Hotal_images3',
        ),
        migrations.RemoveField(
            model_name='add_hotal',
            name='Hotal_images4',
        ),
        migrations.RemoveField(
            model_name='add_hotal',
            name='Hotal_images5',
        ),
        migrations.AddField(
            model_name='add_hotal',
            name='hotal_new_price_premium',
            field=models.CharField(default='', max_length=255),
        ),
    ]
