# Generated by Django 4.1 on 2022-10-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0003_remove_add_hotal_hotal_images2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='exclusive_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('exclusive_partners_images1', models.ImageField(blank=True, null=True, upload_to='exclusive_partners')),
                ('exclusive_partners_images2', models.ImageField(blank=True, null=True, upload_to='exclusive_partners')),
                ('exclusive_partners_images3', models.ImageField(blank=True, null=True, upload_to='exclusive_partners')),
                ('exclusive_partners_images4', models.ImageField(blank=True, null=True, upload_to='exclusive_partners')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('Holiday_packages_images1', models.ImageField(blank=True, null=True, upload_to='Holiday_packages')),
                ('Holiday_packages_images2', models.ImageField(blank=True, null=True, upload_to='Holiday_packages')),
                ('Holiday_packages_images3', models.ImageField(blank=True, null=True, upload_to='Holiday_packages')),
                ('Holiday_packages_images4', models.ImageField(blank=True, null=True, upload_to='Holiday_packages')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('promotions_images1', models.ImageField(blank=True, null=True, upload_to='promotions')),
                ('promotions_images2', models.ImageField(blank=True, null=True, upload_to='promotions')),
                ('promotions_images3', models.ImageField(blank=True, null=True, upload_to='promotions')),
                ('promotions_images4', models.ImageField(blank=True, null=True, upload_to='promotions')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
