# Generated by Django 4.1 on 2022-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0005_remove_exclusive_partners_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promotions_images1',
            field=models.ImageField(blank=True, null=True, upload_to='promotion'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotions_images2',
            field=models.ImageField(blank=True, null=True, upload_to='promotion'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotions_images3',
            field=models.ImageField(blank=True, null=True, upload_to='promotion'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotions_images4',
            field=models.ImageField(blank=True, null=True, upload_to='promotion'),
        ),
    ]
