# Generated by Django 4.1 on 2022-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0006_alter_promotions_promotions_images1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='whats_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whats_new_images1', models.ImageField(blank=True, null=True, upload_to='whats_new')),
                ('whats_new_images2', models.ImageField(blank=True, null=True, upload_to='whats_new')),
                ('whats_new_images3', models.ImageField(blank=True, null=True, upload_to='whats_new')),
                ('whats_new_images4', models.ImageField(blank=True, null=True, upload_to='whats_new')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
